### ISSUE TITLE
no vertical scroll bars

### ISSUE THREAD

**Issue by k7ki** [Exalm/modern2#1]
On Linux, Seamonkey v2.40 (--enable-default-toolkit=cairo-gtk3), there are no vertical scroll bars. Windows is OK and the default theme on both OS's is OK.

**Comment by alice-mkh** [comment]
Hello. I use a GTK2-based build, so I don't see that. However, I've seen problems with scrollbars with Default theme on a GTK3 build. Does default Modern theme have the same issues?

**Comment by alice-mkh** [comment]
Also it may depend on your GTK3 version.

**Comment by k7ki** [comment]
Oh, but I get same no scrollbars with the gtk2 2.40 build. The gtk3 one is the nightly build I am using, sorry. My linux systems have gtk2-2.24.30-1.fc23.x86_64 and gtk3-3.18.9-1.fc23.x86_64.
 The default Modern does not have the issue for both gtk2 and gtk3 build.

**Comment by alice-mkh** [comment]
Hmm. That seems weird, since it works fine for me. I guessed it was just another GTK3 problem. I'll look into it when I get home.

**Comment by k7ki** [comment]
Also, I've disabled all addons and made sure the zoom level is 100%. No change for either gtk2 or gtk3.

**Comment by alice-mkh** [comment]
What also may be of importance is the scrollbar steppers configuration and about:config settings.

**Comment by k7ki** [comment]
scrollbar steppers? I don't know what that is. In about:config all scrollbar configs are default. I use KDE Plasma. I tried Gnome and there was no change.

**Comment by alice-mkh** [comment]
I mean those <>-----======------<> little arrows.
In KDE they can easily be configured: <-----======------>
-----======------<>
<-----======------<>
-----======------

SeaMonkey follows that settings, and maybe the theme has a funny bug with some configuration.

**Comment by k7ki** [comment]
The default theme for gtk2 and gtk3 applicaions is set to Adwaita, which I read, doesn't include scroll arrows. KDE allows me to change that. I installed and am using a non-Adwaita theme for gtk3 applications. Restarted Seamonkey  with Modern2 and wala... the scrollbars are back. So an issue with working with the Adwaiter theme. Since I use KDE this is a mostly a non issue for me now but the Modern2 should work with that theme.

**Comment by alice-mkh** [comment]
I suspect there is a problem when you have all the steps invisible. I think I even the know the reason.

**Comment by alice-mkh** [comment]
More precisely, scrollbar minimal width is specified for the steppers, but not the trough, making it have 0px width when no steppers are visible.

**Comment by k7ki** [comment]
Reply lag. For gtk applications I don't have the control over the arrows in KDE. Would have to use the tweak tool maybe. I know that gnome has been stripped down greatly for configuring the look and feel of most things. maybe gtk config?

**Comment by alice-mkh** [comment]
Perhaps the config is theme-specific. I know for sure you can do that with Oxygen, Breeze and QtCurve.

**Comment by k7ki** [comment]
Do other themes such as the built in Modern not rely on the desktop theme?
Yes KDE is great for adjusting things but this is a gtk application. There used to be a setting to use KDE controls/widgets for gtk apps, but I don't see it any more.

**Comment by alice-mkh** [comment]
These settings affect GTK apps as well, and you don't have the control over that in SM themes. Anyway, it's just a bug which I'll fix, it just happens to only show up on certain configurations.

**Comment by k7ki** [comment]
Thanks!

**Comment by k7ki** [comment]
This solves the no steppers in gtk themes:
~/.config/gtk-3.0/gtk.css
.scrollbar {
-GtkScrollbar-has-backward-stepper: 1;
-GtkScrollbar-has-forward-stepper: 1;
-GtkRange-slider-width: 15;
-GtkRange-stepper-size: 20;
}

**Comment by alice-mkh** [comment]
Yes. You don't even have to specify all of them, a single -GtkScrollbar-has-forward-stepper: 1; or a back one would do it.

**Comment by alice-mkh** [comment]
https://github.com/Exalm/modern2/commit/e52197002a8b264029531716a2efa8020579b7e6
