### ISSUE TITLE
Modern2 v0.4.3 and SM v2.49.1

### ISSUE THREAD

**Issue by k7ki** [Exalm/modern2#3]
With Modern2 0.4.3 used with the newly released SM 2.49.1,
replying to an email message, the composition does not have the content
of the message being replied to. I tried both HTML and plain text, no
difference.

**Comment by alice-mkh** [comment]
Hi. https://github.com/Exalm/gnomerunner/issues/12

В Пятница, 10 ноя. 2017 в 9:07 Д. П., Kevin Simmons 
<notifications@github.com> написал:

**Comment by alice-mkh** [comment]
https://github.com/Exalm/modern2/commit/4cea56ac958f03f0ca9a950ede753d67ba2c9b24
